tasks:
  - source: load.py
    product:
      nb: products/load.html
      raw: products/raw

  - source: plot.py
    product:
      nb: products/plot.html


  - source: train.py
    name: train-[[width]]
    product:
      nb: products/train-[[width]].html
      model: products/model-[[width]].pth
    params:
      test: false
    grid:
      width: [6, 12, 18, 24, 32]
